### ISSUE TITLE
Continues to detect after activity is closed

### ISSUE THREAD

**Issue by ptrbrynt** [nisrulz/sensey#26]
I've called `Sensey.getInstance().stopWristTwistDetection(wristTwistListener)` in `onPause()` and `onStop()`, and I've also called `Sensey.getInstance().stop()` in `onDestroy()`. Am I missing anything?

**Comment by nisrulz** [comment]
@peter-rotacloud can you share more information like logcat logs which shows the sensey detection is happening even after your activity is closed. You are probably keeping it active somewhere, because technically if say you didnot call `Sensey.getInstance().stop()` in `onDestroy()` what you will be doing is leaking memory. The system anyways shuts down all functional execution for the activity as per the lifecycle of activity.
